# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Forty
title-normal: by HTML5 UP
description: The Jekyll version of the Forty theme by HTML5 UP.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "http://www.zac-heisey.com" # the base hostname & protocol for your site
author:

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: forestryio
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      description: ""
      image: ""
      categories: ""
      tags: []
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      description: ""
      image: ""
  - scope:
      path: ""
      type: products
    values:
      layout: product
      description: ""
      banner-image: ""
      primary-headline: ""
      primary-content: ""
      content-blocks:
        - heading: ""
          blurb: ""
          image: ""
          link: ""
