---
# Site settings
title: RISE Prime Wellness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  products:
    output: true  
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      categories: blog
      featured-image: ''
      permalink: "/:categories/:title"
      description: ''
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      description: ''
      featured-image: ''
  - scope:
      path: ''
      type: products
    values:
      layout: product
      description: ''
      banner-image: ''
      primary-headline: ''
      primary-content: ''
      content-blocks:
        - heading: ''
          blurb: ''
          image: ''
          link: ''
url: https://prime-wellness.netlify.com
baseurl:
email: admin@riseprimewellness.com
description: Welcome to RISE Prime Wellness in San Diego.

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Build settings
markdown: kramdown
permalinks: pretty
include:
- _redirects
