---
title: RISE Prime Wellness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    description: ''
    categories: blog
    seo-title: ''
    seo-description: ''
    featured-image: ''
    permalink: "/:categories/:title"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description: ''
    seo-title: ''
    seo-description: ''
    featured-image: ''
subtitle: 
url: https://www.riseprimewellness.com
baseurl: 
email: rise@riseprimewellness.com
description: Welcome to RISE Prime Wellness in San Diego. Visit us online to learn
  more about physical therapy, yoga, and cryotherapy treatment options.
logo_image: uploads/rise-prime-logo2.svg
tiles-source: pages
tiles-count: 4
markdown: kramdown
permalink: pretty
include:
- _redirects
