---
title: DEV_RISE Prime Wellness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    description: ''
    categories: blog
    seo-title: ''
    seo-description: ''
    featured-image: ''
    permalink: "/:categories/:title"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description: ''
    seo-title: ''
    seo-description: ''
    featured-image: ''
- scope:
    path: ''
    type: products
  values:
    layout: product
    description: ''
    banner-image: ''
    primary-headline: ''
    primary-content: ''
    content-blocks:
    - heading: ''
      blurb: ''
      image: ''
      link: ''
url: https://prime-wellness.netlify.com
baseurl:
email: admin@riseprimewellness.com
description: Welcome to RISE Prime Wellness in San Diego.
tiles-source: pages
tiles-count: 6
markdown: kramdown
permalink: pretty
include:
- _redirects
